server:
  port: 8081

spring:
  application:
    name: smart-home-light-service
  ai:
    mcp:
      server:
        name: smart-home-light-service
        version: 0.0.1

logging:
  level:
    com.noinch.mcp.demo.smarthome.server.light: debug
    root: info