server:
  port: 8082

spring:
  application:
    name: smart-home-lock-service
  ai:
    mcp:
      server:
        name: smart-home-lock-service
        version: 0.0.1

logging:
  level:
    com.noinch.mcp.demo.smarthome.server.lock: debug
    root: info
